import './globals.css'
import Header from '@/Components/header';
import Footer from '@/Components/footer';
import { Open_Sans, Playfair_Display } from 'next/font/google';


export const metadata = {
  title: 'VVGC Temple',
  description: 'Generated by create next app',
}

const opensans = Open_Sans({ subsets: ['latin'], variable: '--font-opensans', fallback: 'sans' });
const playfair = Playfair_Display({ subsets: ['latin'], variable: '--font-playfair', fallback: 'serif' });

export default function RootLayout({ children }) {

  return (
    <html lang="en" >
      <body className={`${opensans.variable} font-sans box-border bg-gradient-to-tr from-slate-200 via-blue-50 to-orangr-100`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
